baseurl: https://valh.io
languageCode: en-us
theme: hugo-theme_clean-blog-custom
# theme: clean-blog-local
pagination:
  pagerSize: 7
title: Blog

permalinks:
  post: /p/:slug/
  page: /:slug/

outputs:
  home:
    - html
    - rss
    - json

taxonomies:
  tag: tags

params:
  default_author: Valentin Heidelberger
  description: The personal blog of Valentin Heidelberger
  nav:
    # bell: true
    logo: true
    title: Valentin Heidelberger # Displayed on the navbar's left side
    search: true # Display link to search in navbar
    aboutme: true
  header_img: /img/dall_e_1.webp
  taxonomy_header_imgs:
    cheatsheet: linux.webp
    data: data.webp
    docker: docker.png
    homeassistant: home.webp
    homeserverpi: raspberrypi.webp
    linux: linux.webp
    music: vinyl.webp
    raspberrypi: raspberrypi.webp
    technology: rz.webp
  fourofour_img: /img/404.webp
  # featured_tags:
  #     - linux
  #     - raspberrypi
  #     - homeassistant
  #     - data
  #     - cheatsheet
  mainSections:
    - post
  featuredImageField: header_img
  rssFullContent: true
  favicon: /img/favicon.ico
  post_age_warning_years: 3

  footer:
    copyright_name: Valentin Heidelberger
    since: 2017
    customText:
    rss: true
    hugo_credit: true
    theme_credit: true
    social:
      linkedin_username : va1entin
      discogs_username: va1entin
      github_username:  va1entin
      gitlab_username: va1entin
      # mastodon_instance: mastodon.social
      # mastodon_username: valh

  dateFormat:
    published: January 02, 2006
    lastUpdated: January 02, 2006 15:04 MST

  article:
    math: false
    license:
      enabled: true
      default: Licensed under CC BY 4.0

  # Respect CSS @media property prefers-color-scheme, automatically switches themes based on users OS theme or user agent
  respect_prefers_color_scheme: true

  imageProcessing:
    cover:
      enabled: true
    content:
      enabled: true

markup:
  tableOfContents:
    startLevel: 1
    ordered: false
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true

pygmentsUseClasses: true
